### ISSUE TITLE
Where to Run 

### ISSUE THREAD

**Issue by chittuchavan** [aurghya/Auditorium-and-Room-Booking-System#1]
Im new to java can you please guide me how to run this !

**Comment by aurghya** [comment]
Download and install NetBeans IDE. Create a New Project, and then choose Java Web as the category and Web Application with Existing Sources as the project. Specify the location of the Project Folder, select server and settings (GlassFish Server 4.1.1), enter location of the WEB-INF folder (in build/web). You will also need MySQL_JDBC Driver to connect to the mysql database (change the name of the database and its corresponding details in Connect.java).
